FROM php:8.1.3-fpm-alpine

RUN apk update; \
    apk upgrade;

RUN apk --no-cache add --virtual .build-deps $PHPIZE_DEPS \
        && apk --no-cache add --virtual .ext-deps \
        libzip-dev  \
        libpq-dev \
        libpng-dev \
        libxslt-dev \
        imap-dev \
        zip \
        jpegoptim optipng pngquant gifsicle \
        unzip \
        bash \
        git \
        curl \
        wget 
    
RUN docker-php-ext-install pdo pdo_pgsql pgsql pcntl bcmath opcache 
RUN apk del .build-deps

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

RUN apk --no-cache add --virtual .build-deps $PHPIZE_DEPS 
RUN pecl install xdebug && docker-php-ext-enable xdebug
RUN apk del .build-deps

#Add custom php ini setting to other settings
ADD ./docker/config/php/* /usr/local/etc/php/conf.d/

USER 1000


